version: '3'

vars:
  BINARY_NAME: 'gosrcobfsc'

tasks:
  default:
    cmds:
      - task --list-all

  build:
    cmds:
      - go build -o {{.BINARY_NAME}} ./cmd/main.go

  test:
    cmds:
      - gotestsum -- -v ./internal/...

  test-integration:
    cmds:
      - cmd: echo "Building..."
      - task: build
      - cmd: echo "Deleting previous test run."
      - cmd: find ./tests -mindepth 1 ! -name '.gitkeep' -delete
      - cmd: ./{{.BINARY_NAME}} --moduleName=gosrcobfsc --source=/home/ada/repos/gosrcobfsc --sink=/home/ada/repos/gosrcobfsc/tests
      - cmd: echo "Building project in obfuscated directory."
      - cmd: (cd /home/ada/repos/gosrcobfsc/tests && go build ./cmd/main.go)
      - cmd: echo "Running tests in obfuscated directory."
      - cmd: (cd /home/ada/repos/gosrcobfsc/tests && go test ./...)
    silent: true

